### ISSUE TITLE
How to load those models

### ISSUE THREAD

**Issue by engahmed1190** [jayanthkoushik/neural-style-models#1]
Hi , 
   I am having an issue to load these models they are weight models only and no model.JSON 

can you please help me 

Thanks

**Comment by engahmed1190** [comment]
```
        from keras.models import load_model
	base_model=load_model('kandinsky_x.h5')
```
	
	
here is the error
```
	Using TensorFlow backend.
	Traceback (most recent call last):
	File "/home/deeplearning/Desktop/PythonScripts/Load_Keras_model.py", line 2, in <module>
	base_model=load_model('kandinsky_x.h5')
	File "/usr/local/lib/python2.7/dist-packages/keras/models.py", line 238, in load_model
	raise ValueError('No model found in config file.')
	ValueError: No model found in config file.
```

**Comment by jayanthkoushik** [comment]
Yes, these files only contain weights. You should first create the model. Refer to [this](https://github.com/jayanthkoushik/neural-style/blob/master/neural_style/fast_neural_style/transformer_net.py#L78). The function defines the model architecture. Once you create the model, you can load the weights from the files in this repository.
